"""Color palette presets and theme catalog for Betteragy."""

from .theme_model import ThemeDefinition

THEME_CATALOG: dict[str, ThemeDefinition] = {
    "warm": ThemeDefinition(
        id="warm",
        name="Gruvbox Warm",
        description="Warm ivory, terracotta rust, forest green & amber",
        primary="bold #af3a03",
        secondary="bold #d79921",
        border_style="#bdae93",
        cursor_style="bold #af3a03",
        title_style="bold #af3a03",
        subtitle_style="bold #79740e",
        header_style="bold #af3a03",
        sel_style="bold #fbf1c7 on #af3a03",
        dim_style="#7c6f64",
        quota_high="#16a34a",
        quota_high_track="#86efac",
        quota_mid="#d97706",
        quota_mid_track="#fde68a",
        quota_low="#dc2626",
        quota_low_track="#fca5a5",
        active_badge="[bold #16a34a][*] Active[/bold #16a34a]",
        ready_badge="[#15803d][+] Ready[/#15803d]",
        cooldown_badge="[#b45309][!] Cooldown[/#b45309]",
        disabled_badge="[dim #dc2626][x] Disabled[/dim #dc2626]",
    ),
    "emerald": ThemeDefinition(
        id="emerald",
        name="Emerald Forest",
        description="Lush emerald green, mint accents & sage borders",
        primary="bold #10b981",
        secondary="bold #34d399",
        border_style="#059669",
        cursor_style="bold #10b981",
        title_style="bold #10b981",
        subtitle_style="bold #6ee7b7",
        header_style="bold #047857",
        sel_style="bold white on #065f46",
        dim_style="#6b7280",
        quota_high="#22c55e",
        quota_high_track="#86efac",
        quota_mid="#f59e0b",
        quota_mid_track="#fde68a",
        quota_low="#ef4444",
        quota_low_track="#fca5a5",
        active_badge="[bold #22c55e][*] Active[/bold #22c55e]",
        ready_badge="[#10b981][+] Ready[/#10b981]",
        cooldown_badge="[#f59e0b][!] Cooldown[/#f59e0b]",
        disabled_badge="[dim #ef4444][x] Disabled[/dim #ef4444]",
    ),
    "cyber": ThemeDefinition(
        id="cyber",
        name="Cyber Dark",
        description="Neon cyan, electric magenta & dark slate",
        primary="bold cyan",
        secondary="bold magenta",
        border_style="cyan",
        cursor_style="bold cyan",
        title_style="bold cyan",
        subtitle_style="bold magenta",
        header_style="bold magenta",
        sel_style="bold cyan on #1e293b",
        dim_style="dim white",
        quota_high="#22c55e",
        quota_high_track="dim #22c55e",
        quota_mid="#eab308",
        quota_mid_track="dim #eab308",
        quota_low="#ef4444",
        quota_low_track="dim #ef4444",
        active_badge="[bold green][*] Active[/bold green]",
        ready_badge="[green][+] Ready[/green]",
        cooldown_badge="[yellow][!] Cooldown[/yellow]",
        disabled_badge="[dim red][x] Disabled[/dim red]",
    ),
    "dracula": ThemeDefinition(
        id="dracula",
        name="Dracula",
        description="Vibrant purple, pastel pink & soft cyan",
        primary="bold #bd93f9",
        secondary="bold #ff79c6",
        border_style="#6272a4",
        cursor_style="bold #ff79c6",
        title_style="bold #bd93f9",
        subtitle_style="bold #ff79c6",
        header_style="bold #bd93f9",
        sel_style="bold #f8f8f2 on #44475a",
        dim_style="#6272a4",
        quota_high="#50fa7b",
        quota_high_track="dim #50fa7b",
        quota_mid="#f1fa8c",
        quota_mid_track="dim #f1fa8c",
        quota_low="#ff5555",
        quota_low_track="dim #ff5555",
        active_badge="[bold #50fa7b][*] Active[/bold #50fa7b]",
        ready_badge="[#50fa7b][+] Ready[/#50fa7b]",
        cooldown_badge="[#f1fa8c][!] Cooldown[/#f1fa8c]",
        disabled_badge="[dim #ff5555][x] Disabled[/dim #ff5555]",
    ),
    "monokai": ThemeDefinition(
        id="monokai",
        name="Monokai Pro",
        description="Sunny yellow, lime green & burnt orange",
        primary="bold #ffd866",
        secondary="bold #a9dc76",
        border_style="#727072",
        cursor_style="bold #ffd866",
        title_style="bold #ffd866",
        subtitle_style="bold #fc9867",
        header_style="bold #ffd866",
        sel_style="bold #221f22 on #ffd866",
        dim_style="#727072",
        quota_high="#a9dc76",
        quota_high_track="dim #a9dc76",
        quota_mid="#fc9867",
        quota_mid_track="dim #fc9867",
        quota_low="#ff6188",
        quota_low_track="dim #ff6188",
        active_badge="[bold #a9dc76][*] Active[/bold #a9dc76]",
        ready_badge="[#a9dc76][+] Ready[/#a9dc76]",
        cooldown_badge="[#fc9867][!] Cooldown[/#fc9867]",
        disabled_badge="[dim #ff6188][x] Disabled[/dim #ff6188]",
    ),
    "nord": ThemeDefinition(
        id="nord",
        name="Nord Arctic",
        description="Polar night, frost ice blue & aurora green",
        primary="bold #88c0d0",
        secondary="bold #81a1c1",
        border_style="#4c566a",
        cursor_style="bold #88c0d0",
        title_style="bold #88c0d0",
        subtitle_style="bold #81a1c1",
        header_style="bold #5e81ac",
        sel_style="bold #eceff4 on #3b4252",
        dim_style="#4c566a",
        quota_high="#a3be8c",
        quota_high_track="dim #a3be8c",
        quota_mid="#ebcb8b",
        quota_mid_track="dim #ebcb8b",
        quota_low="#bf616a",
        quota_low_track="dim #bf616a",
        active_badge="[bold #a3be8c][*] Active[/bold #a3be8c]",
        ready_badge="[#a3be8c][+] Ready[/#a3be8c]",
        cooldown_badge="[#ebcb8b][!] Cooldown[/#ebcb8b]",
        disabled_badge="[dim #bf616a][x] Disabled[/dim #bf616a]",
    ),
    "monochrome": ThemeDefinition(
        id="monochrome",
        name="Modern Minimal",
        description="Clean monochrome slate with minimal accents",
        primary="bold white",
        secondary="bold #d4d4d8",
        border_style="#71717a",
        cursor_style="bold white",
        title_style="bold white",
        subtitle_style="dim white",
        header_style="bold white",
        sel_style="reverse bold",
        dim_style="#71717a",
        quota_high="#16a34a",
        quota_high_track="#86efac",
        quota_mid="#ca8a04",
        quota_mid_track="#fef08a",
        quota_low="#dc2626",
        quota_low_track="#fca5a5",
        active_badge="[bold #16a34a][*] Active[/bold #16a34a]",
        ready_badge="[#16a34a][+] Ready[/#16a34a]",
        cooldown_badge="[#ca8a04][!] Cooldown[/#ca8a04]",
        disabled_badge="[dim #dc2626][x] Disabled[/dim #dc2626]",
    ),
}
